### ISSUE TITLE
Doesn't support multi-line expansion

### ISSUE THREAD

**Issue by joelclimbsthings** [unobserved-io/espanso-gui#3]
Thanks for the software! I just installed, and noticed that the multi-line expansion that I have doesn't display in the field. I'm fairly new to expanso, so it may be that I'm doing something wrong as well--although it works via the usual espanso functionality.

**Comment by rickykresslein** [comment]
Yes, that's correct. Unfortunately, Iced (the framework espansoGUI uses) doesn't support multi-line text input yet, I believe it is planned in the next few months. As soon as it is available upstream I will add support to espansoGUI.

**Comment by beedell-roke** [comment]
> https://github.com/unobserved-io/espanso-gui/issues/3#issuecomment-1738503218

@rickykresslein, have you a link to the issue tracking that?

**Comment by rickykresslein** [comment]
@RokeJulianLockhart Yes, and it looks like it was just implemented about a month ago! I'll get working on adding this ability to espansoGUI asap. https://github.com/iced-rs/iced/issues/320

**Comment by WinnerWind** [comment]
Hi there! Is multiline support on the way? I'm looking to simplify coding by using Espanso to quickly input huge functions.

**Comment by rickykresslein** [comment]
Hi @WinnerWind, yes I am working on it. Unfortunately, the way Iced implemented this is to introduce a completely new widget that is a text editor box rather than just adding multi-line support to the already existing text input espansoGUI uses. The way text is processed through the text editor is different than the current input box, so I'm working on changing the system to work with this new text editor box. 

Hopefully I can get it figured out, and as soon as I do I will update this thread. Thanks for sticking with me!

**Comment by rickykresslein** [comment]
Never mind, I spoke too soon. I figured it out and just pushed a commit. I will put out a release as soon as I get some time.
