### ISSUE TITLE
Attempting to open base.yml file causes espansogui to crash

### ISSUE THREAD

**Issue by ajmarkow** [unobserved-io/espanso-gui#5]
Love the app! I'm able to create new snippets by creating a new file, but attempting to open my base.yml causes the application to crash. I've attached a screen recording, and system info:

System Info:

![CleanShot 2023-10-04 at 12 40 35-CST@2x](https://github.com/unobserved-io/espanso-gui/assets/66390428/2c900b71-3215-4f73-b5b4-60254e652d2a)

Screen Recording:

![CleanShot 2023-10-04 at 12 43 12-CST](https://github.com/unobserved-io/espanso-gui/assets/66390428/bba93ac1-fccb-4a60-8e7e-825923b3efe1)

**Comment by rickykresslein** [comment]
Thanks! I'm glad you are finding it useful. The crash you are having is probably linked to issue #1. This is already fixed in the code, but I haven't released a new version yet. I'll check back here once the new version is out to see if the problem goes away. I just moved so I've been super busy, but I'll get it out as soon as I can. Thanks for bringing this to my attention!

**Comment by rickykresslein** [comment]
I released the new version a couple days ago. I'd really appreciate it if you could test it and let me know if this is fixed.
